### PR TITLE
DR quality utils fonction

### PR DESCRIPTION
**Pull request by lgatto**
Two small utility functions that allow to call `red_rnx_auc()` and `eval_dr_quality()` directly on the high- and low-dimensional data matrices, rather than the pairwise distances. `eval_dr_quality_from_data()` and `eval_red_rnx_auc_from_data()` simply call `eucl_dist_matr()` on the data matrices and pass the results to the respective DR quality functions.

They are particularly useful for the [fmsne](https://github.com/lgatto/fmsne) R package, so as to perform all computations on the Python side in a single call, rather than computing the pairwise distances in R or call the Python code twice with data and pairwise matrices.

### CODE REVIEW

**Comment by cdebodt** [comment]
Great, thanks!

`eval_dr_quality_from_data()` is correct but `eval_red_rnx_auc_from_data()` is not; it relies on `red_rnx_auc()` which does not work with distance matrices but directly with HD and LD data coordinates. 

`red_rnx_auc()` (in fmsne.py) aims to avoid computing the full HD and LD distance matrices, which brings O(N^2) time complexity  with N data samples and is unaffordable with large data sets. It employs vantage-point trees in both HD and LD spaces to identify the `Kup` nearest neighbors of each data point, according to Euclidean distances in both HD and LD spaces. The full quality curves are not computed (O(N^2) time complexity) but instead evaluated for neighborhood sizes ranging from 1 to `Kup` (O(Kup * N * log(N)) time complexity).

I believe `eval_red_rnx_auc_from_data()` should then just use `red_rnx_auc()` with the HD and LD data sets, without calling `eucl_dist_matr()`.

**Comment by lgatto** [comment]
Thank you, and sorry for the silly mistake, I'll fix this.

But before that, what are the advantages of eval_dr_quality()
over red_rnx_auc()?  I imagine that it is more precise in its
distances, and hence in the computation of the intersection
between the v_i^K and n_i^K?  If so, is the cost in time
complexity worth it?

In my use cases, I tend to compare the DR quality between PCA,
t-SNE, and at least one of your multi-scale methods. This means
that if I call eval_dr_quality() as it is now, I will repeat the
distances calculation in HD as many time as I have LD embeddings,
when only one is really needed. In addition, in modern
single-cell RNA sequencing experiments (my first use-case),
sample sizes are most of the time in the 1000s, if not 10000s of
cells.

I am considering focusing on red_rnx_auc(), at least in a first
stage. What do you think?

**Comment by lgatto** [comment]
Comparing the Rx metrics computed with `eval_dr_quality()` and `red_rnx_auc()`, there are some minor differences for a minority of values, which seem to confirm that the prioritising the latter is probably the right approach. Let me know what you think.

Depending on this, I might need to add some additional utility functions. I was wondering whether you preferred me to add them directly to the `fmsne` python package, or whether they should find a home somewhere else (for example a `fmsneutils` package). The advantage adding them here is that you'll get a chance to review them.

**Comment by cdebodt** [comment]
Sorry for my late reply; here are some differences:

`eval_dr_quality()`:
- Computes $R_{NX}(K)$ for $K=1,2, ..., \mathbf{N-2}$ (**exactly**, using the true HD and LD neighborhoods of the data points, **without approximation**)
- It returns $R_{NX}(K)$ for $K=1,2, ..., N-2$ and its $AUC$ (computed using a log scale for $K$)
- Its time complexity is $\mathcal{O}(N^2 \log(N))$

`red_rnx_auc()`:
- Computes $R_{NX}(K)$ for $K=1,2, ..., \mathbf{Kup}$ (**exactly**, using the true HD and LD neighborhoods of the data points, **without approximation**), with $Kup$ an integer such that $Kup \geq 1$ and $Kup \leq N-2$
- It returns $R_{NX}(K)$ for $K=1,2, ..., Kup$ and the $AUC$ of the associated curve (computed using a log scale for $K=1,2, ..., Kup$)
- Its time complexity is $\mathcal{O}(Kup \cdot N \log(N))$
- $Kup$ is a parameter of `red_rnx_auc()`; if $Kup \ll N$, the time complexity becomes $\mathcal{O}(N \log(N))$. In the paper, for the experiments on large-scale databases ($N\gg 10^4$), we set $Kup$ to $10^4$, to consider neighborhoods up to similar sizes as the ones considered when dealing with moderate-sized databases ($N\leq 10^4$).

For large data sets, `red_rnx_auc()` is hence much faster than `eval_dr_quality()`. 

On the other hand, `red_rnx_auc()` only computes the $R_{NX}(K)$ curve for neighborhood sizes $K$ smaller than $Kup$. If $Kup\ll N$, you do not quantify the preservation of neighborhood sizes ranging from $Kup+1$ to $N-2$; therefore, you do not quantify the quality of the LD embedding in terms of global structure preservation (larger neighborhood sizes), and instead focus on local aspects (smaller neighborhoods). The $AUC$ of $R_{NX}(K)$ for $K=1,2, ..., Kup$ hence favors dimensionality reduction (DR) methods that are more local than global, e.g., single-scale neighbor embedding methods vs multi-scale ones, compared to the $AUC$ of the full $R_{NX}(K)$ curve (for $K=1,2, ..., N-2$). It is also noteworthy that the $AUC$ of the full $R_{NX}(K)$ curve (for $K=1,2, ..., N-2$) is computed using a log scale for the neighborhood size $K$; smaller neighborhoods (i.e., local structure preservation) are hence already favored when computing the the $AUC$ of the full $R_{NX}(K)$ curve (for $K=1,2, ..., N-2$). The $AUC$ of the reduced $R_{NX}(K)$ curve (for $K=1,2, ..., Kup$) hence further favors local DR methods over global ones. 

Despite this, the experiments in the paper show that multi-scale methods are superior to single-scale ones, on both moderate-sized databases ($N \leq 10^4$; DR quality is quantified using the full $R_{NX}(K)$ curve, for $K=1,2, ..., N-2$) and large-scale data sets ($N\gg 10^4$; DR quality is quantified using the reduced $R_{NX}(K)$ curve, for $K=1,2, ..., Kup$).

Whether to employ `eval_dr_quality()` or `red_rnx_auc()` hence depends on the size of your databases and the time you have to conduct your experiments; I would say that as long as $N\leq 10^4$, you can go with `eval_dr_quality()` (which quantifies the preservation of all neighborhood sizes, from local to global ones), unless `red_rnx_auc()` is much faster and you prefer to speed up the evaluation of DR quality over computing the full $R_{NX}(K)$ curve (for $K=1,2, ..., N-2$, which better quantifies the preservation of global structures). When $N\gg 10^4$, `red_rnx_auc()` must be employed, due to the time complexity of `eval_dr_quality()`. 

Regarding the computation of HD distances when comparing several LD embeddings (from different DR methods) of a single HD data set:
- `red_rnx_auc()` indeed computes the same HD distances (with the $Kup$ HD neighbors of each data point) each time it is called (using a different LD embedding), since it takes the HD and LD coordinates directly as parameters and does not compute the full HD and LD distance matrices. 
- `eval_dr_quality()` enables you to avoid repeating the computation of the HD distance matrix, as it takes the HD and LD distance matrices as parameters. But if you work with `eval_dr_quality_from_data()` (to perform all computations on the Python side in a single call, as you explained above), you will indeed need to repeat the computation of the HD distance matrix as many times as you have LD embeddings.

All in all, I think that focusing on `red_rnx_auc()` in a first stage is totally fine, if it saves you some computation time; nothing prevents employing `eval_dr_quality()` afterwards, when running "final" experiments. The results should remain very similar, as you noticed. 

As to adding additional utility functions, I think I would add them here (directly to the `fmsne` python package) since things remain quite related. But I let you decide as you prefer, of course! :-)

Hope this helps; don't hesitate if something is not clear, and many thanks again for everything!

**Comment by lgatto** [comment]
Thank you very much for these explanations, that I also used to
amend the R manual page. Based on your comments, I'll update the
PR with a fix for `eval_red_rnx_auc_from_data(X, Y, Kup)` and a
new utility function `eval_dr_quality_from_list(X, Ys)`, that
take a list of LD embeddings Ys, and runs `eval_dr_quality()` for
each pair (X, Yi). This function avoids recomputing the HD
distances `eucl_dist_matr(X)` for each quality assessment.

**Pull request merged**
